118 feature/walk record page api
prgrms-web-devcourse-final-project/WEB1_1_DDang_FE pull request #133
Opened 2024-12-06 06:06 UTC by wonill

## ✅ PR Checklist

- [ ] 불필요한 코드 중복이 없습니다.
- [ ] 민감한 정보를 포함하지 않았습니다.
- [ ] 불필요한 콘솔 로그나 주석을 포함하지 않았습니다.
- [ ] 컴포넌트 key값에 고유한 값을 할당했습니다.

## 📝 Summary

🔗 **ISSUE** : #118 

산책 기록 페이지 데이터 바인딩 후 리액트 쿼리와 에러바운더리 적용했습니다.

## 🖼️ Screenshots

2024-12-06 06:23 UTC, shlee9999 requested changes

2024-12-06 06:23 UTC, shlee9999 commented on src/apis/log/fetchFamilyYearlyWalks.ts
> +export type FamilyYearlyWalksRequest = void
사용하지 않는 것 같은데 지워주시면 될 것 같습니다?

2024-12-06 06:23 UTC, shlee9999 commented on src/apis/log/fetchMonthlyWalks.ts
> +export type MonthlyWalksRequest = void
마찬가지로 지워주시면 될 것 같아요

2024-12-06 06:23 UTC, shlee9999 commented on src/apis/log/fetchTotalWalkRecords.ts
> +export type TotalWalkRecordsRequest = void
마찬가지로 지워주시면 될 것 같아요

2024-12-06 06:23 UTC, shlee9999 commented on src/apis/log/fetchWalkDates.ts
> +export type WalkDatesRequest = void
마찬가지로 지워주시면 될 것 같아요

2024-12-06 06:23 UTC, shlee9999 commented on src/utils/positionLabelMap.ts
> +}
constants에 FAMILY_ROLE을 사용하 면 될 것 같아요

2024-12-06 06:25 UTC, wonill commented on src/utils/positionLabelMap.ts
> +}
이미 만들어져있었네요

2024-12-06 06:25 UTC, wonill commented on src/apis/log/fetchFamilyYearlyWalks.ts
> +export type FamilyYearlyWalksRequest = void
넵

2024-12-06 06:25 UTC, wonill commented on src/apis/log/fetchMonthlyWalks.ts
> +export type MonthlyWalksRequest = void
넵

2024-12-06 06:25 UTC, wonill commented on src/apis/log/fetchTotalWalkRecords.ts
> +export type TotalWalkRecordsRequest = void
넵

2024-12-06 06:47 UTC, ruehan submitted a review, later dismissed

2024-12-07 12:50 UTC, shlee9999 approved these changes

2024-12-07 12:50 UTC, ruehan approved these changes

2024-12-07 12:50 UTC, merged