[Desigin] #45 가족 코드 입력 페이지
prgrms-web-devcourse-final-project/WEB1_1_DDang_FE pull request #76
Opened 2024-11-22 08:30 UTC by kimjuyoung99

## ✅ PR Checklist

- [ ] 불필요한 코드 중복이 없습니다.
- [ ] 민감한 정보를 포함하지 않았습니다.
- [ ] 불필요한 콘솔 로그나 주석을 포함하지 않았습니다.
- [ ] 컴포넌트 key값에 고유한 값을 할당했습니다.

## 📝 Summary
#45 🔗 **ISSUE** : 

마이페이지 - 알림 설정 페이지 작업했습니다.

* 모든 알림 조작 시 다른 알람 작동 시나리오 미정
* 헤더 공통컴포넌트 도입 아직 안함

## 🖼️ Screenshots

https://github.com/user-attachments/assets/d92e28cb-f2ff-4ea6-9f7f-a0760cabb70c

2024-11-22 09:30 UTC, wonill approved these changes, later dismissed

2024-11-23 16:45 UTC, shlee9999 requested changes

2024-11-23 16:45 UTC, shlee9999 commented on src/pages/MyPage/SettingModal/styles.ts
> +  background-color: white;
gc_4로 해주세요!

2024-11-23 16:45 UTC, shlee9999 commented on src/pages/MyPage/index.tsx
> +  const handleCloseSteeings = () => {
일단 철자가 안맞습니다ㅠㅠ
closeSettingModal이 적당할 것 같네요
혹시 handle을 앞에 붙이는 이유가 있으실까요??
그리고 저희는 이벤트 핸들러에서 on을 사용하기로 했었습니다

2024-11-23 16:45 UTC, shlee9999 commented on src/pages/MyPage/index.tsx
> +  const handleSettingsClik = () => {
onClickSetting이 적당할 것 같고 철자가 안맞습니다 ㅠ

2024-11-23 16:45 UTC, shlee9999 commented on src/pages/MyPage/SettingModal/index.tsx
> +        <S.CustomQuiteButton $type='semiRoundedRect' $bgColor='gc_4' $fontWeight='700'>
Quite가 아니라 Quit인 것 같습니다

2024-11-23 16:45 UTC, shlee9999 commented on src/pages/MyPage/SettingModal/index.tsx
> +export default function SettingsModal({ isOpen, onClose }: SettingModalProps) {
파일 이름은 SettingModal인데 컴포넌트 이름은 SettingsModal입니다 통일해주세요 
(개인적으로 SettingModal이 나은 것 같습니다)

2024-11-23 16:45 UTC, shlee9999 commented on src/App.tsx
>    min-height: calc(var(--vh, 1vh) * 100);
제가 놓친건지 모르겠는데 --vh가 어느 css 파일에 정의되어있나요?
그리고 vh 말고 dvh로 통일해주세용 😃

2024-11-23 17:00 UTC, kimjuyoung99 commented on src/pages/MyPage/SettingModal/styles.ts
> +  background-color: white;
너무 날카로워서 베일 것 같습니다..

2024-11-23 17:34 UTC, kimjuyoung99 commented on src/pages/MyPage/index.tsx
> +  const handleCloseSteeings = () => {
컨벤션 까먹고 쓰던대로 썼습니다..

2024-11-23 18:02 UTC, kimjuyoung99 commented on src/App.tsx
>    min-height: calc(var(--vh, 1vh) * 100);
아뇨 정의한 적 없습니다 흑흑 제가 바보같이 썼어요
근데 App.tsx의 MobileWrapper 에도 --vh가 있긴 하네요. 여기도 --vh가 정의되지 않아서 1vh가 기본값으로 사용되고 있는 것 같습니다. 나중에 상의하고 바꿔야겠어요

2024-11-24 12:20 UTC, shlee9999 approved these changes, later dismissed

2024-11-24 14:22 UTC, wonill approved these changes

2024-11-24 15:49 UTC, shlee9999 approved these changes

2024-11-24 15:49 UTC, merged