[Design] #21 마이페이지 알림 설정 페이지
prgrms-web-devcourse-final-project/WEB1_1_DDang_FE pull request #81
Opened 2024-11-23 09:45 UTC by kimjuyoung99

## ✅ PR Checklist

- [ ] 불필요한 코드 중복이 없습니다.
- [ ] 민감한 정보를 포함하지 않았습니다.
- [ ] 불필요한 콘솔 로그나 주석을 포함하지 않았습니다.
- [ ] 컴포넌트 key값에 고유한 값을 할당했습니다.

## 📝 Summary

🔗 **ISSUE** : #21 

소셜로그인 페이지 작업했습니다. 
<img width="297" alt="image" src="https://github.com/user-attachments/assets/dcb96f0a-a36b-4292-a6ae-1fec2db22844">

## 🖼️ Screenshots

2024-11-23 11:49 UTC, wonill submitted a review, later dismissed

2024-11-23 16:59 UTC, shlee9999 requested changes

2024-11-23 16:59 UTC, shlee9999 commented on src/pages/LoginPage/index.tsx
> +        <S.Gogle weight='700'>
Google 입니다

2024-11-23 16:59 UTC, shlee9999 commented on src/pages/LoginPage/styles.ts
> +  box-sizing: border-box;
globalStyle에 다 설정해놔서 의미 없을 거에요

2024-11-23 16:59 UTC, shlee9999 commented on src/pages/LoginPage/styles.ts
> +  /* border: 1px solid red; */
이런 주석은 commit 시에는 제거해주세요

2024-11-23 16:59 UTC, shlee9999 commented on src/pages/LoginPage/styles.ts
> +  flex-shrink: 0;
flex-shrink: 0; 이 왜 필요한지 설명해주실 수 있나요?

2024-11-23 17:04 UTC, shlee9999 commented
## 요구사항
1. 브랜치 네이밍 영어로 해주시고, feature, bug, design 다음에 /로 구분해주세요. 다른 분들 꺼 보시면 이해가 될 겁니다.
2. [맞춤법 관련 확장 프로그램](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) 추천해드릴게요
3. 디바이스가 달라지면 화면이 다 깨집니다. 이것 저것 테스트 해보면서 CSS 다시 작성해주세요. 제 홈페이지나 원일님 쪽 참고하시면 도움이 될 것 같아요.

2024-11-23 17:14 UTC, kimjuyoung99 commented
살려주십쇼

2024-11-23 18:22 UTC, kimjuyoung99 commented on src/pages/LoginPage/styles.ts
> +  flex-shrink: 0;
소셜로그인은 정해진 규격이 있다고 해서 설정했어요 디바이스 크기에 따라 조절되게 할까요?

2024-11-24 12:19 UTC, shlee9999 approved these changes, later dismissed

2024-11-24 13:28 UTC, wonill submitted a review, later dismissed

2024-11-24 14:51 UTC, wonill approved these changes

2024-11-24 15:53 UTC, shlee9999 approved these changes

2024-11-24 15:53 UTC, merged