[Design] #28 견주정보 입력 UI 제작
prgrms-web-devcourse-final-project/WEB1_1_DDang_FE pull request #98
Opened 2024-11-27 05:25 UTC by kimjuyoung99

## ✅ PR Checklist

- [ ] 불필요한 코드 중복이 없습니다.
- [ ] 민감한 정보를 포함하지 않았습니다.
- [ ] 불필요한 콘솔 로그나 주석을 포함하지 않았습니다.
- [ ] 컴포넌트 key값에 고유한 값을 할당했습니다.

## 📝 Summary
🔗 **ISSUE** : #28 
* 견주정보 입력 UI 제작
*  아바타 svg 파일 10개를 하나씩 불러오는 것이 불필요하다 느껴 Barrel 패턴을 적용하여 assets 디렉토리에 index파일을 하나 만들어 한꺼번에 export 하였습니다
* 아바타 선택 전 : 버튼 비활성화 / 선택 후 : 버튼 활성화, 컬러 변경
* 아바타 변경 시 아바타 모달에 직전에 선택한 캐릭터 체크표시 유지
* svg파일 몇개가 미묘하게 크기가 작아 따로 스타일 컴포넌트에서 조정 작업 했습니다.
* 스크롤 바 커스텀
* 내일 토스트, 예외처리, 위치등록 구현하겠습니다

## 🖼️ Screenshots
<div align="center">
    <table>
        <tr>
            <td align="center">
                <img src="https://github.com/user-attachments/assets/04268f26-d4f3-4248-919b-cfb0f2e7c04a" width="300" alt="Left Video">
                <br>
            </td>
            <td align="center">
                <img src="https://github.com/user-attachments/assets/dfab832a-e66e-4266-b191-9d5f8e5b97bf" width="300" alt="Right Video">
                <br>
            </td>
        </tr>
    </table>
</div>

2024-11-27 05:38 UTC, kimjuyoung99 commented
@saseungmin 
멘토님 리뷰 살짝 부탁드립니다! 특별히 막히는 부분은 없고 그냥 UI 하나 짠 건데 컴포넌트 구조나 CSS 상대단위 잘 쓰고 있는게 맞는지 궁금합니다..!

2024-11-27 08:50 UTC, wonill submitted a review, later dismissed

2024-11-27 08:50 UTC, wonill commented on src/modals/RegisterAvatarModal/styles.ts
> +export const CustomActionButtonAfter = styled(BaseCustomActionButton)``
여긴 왜 css가 없죠?

2024-11-27 08:54 UTC, shlee9999 requested changes

2024-11-27 08:54 UTC, shlee9999 commented on src/modals/RegisterAvatarModal/index.tsx
> +      </S.HeaderArea>
<Header type="lg" closeBtn onCLickCloseBtn={popModal}/> 이런 형태로 해보시겠어요?

2024-11-27 08:54 UTC, shlee9999 commented on src/pages/RegisterPage/Register/styles.ts
> +    gap: 0.8rem;
의미 있는 css인가요?

2024-11-27 09:00 UTC, kimjuyoung99 commented on src/modals/RegisterAvatarModal/styles.ts
> +export const CustomActionButtonAfter = styled(BaseCustomActionButton)``
Button 공통컴포넌트 default 값인데, Before 버튼이랑 이름 통일성을 주려고 한거에요
이렇게 안하고 그냥 Action 버튼을 import 하면 index.tsx 파일에 Action버튼을 또 import 해주는게 별로여서..
혹시 제가 모르는 다른 방법 있나요?

2024-11-27 09:07 UTC, kimjuyoung99 commented on src/modals/RegisterAvatarModal/index.tsx
> +      </S.HeaderArea>
어떤걸 말씀하시는 건가요?

2024-11-27 09:20 UTC, kimjuyoung78 commented on src/pages/RegisterPage/Register/styles.ts
> +    gap: 0.8rem;
공통컴포넌트랑 구조가 달라 커스텀 한겁니다
 flex-direction: row; -> 성별아이콘, 텍스트 가로정렬
  gap: 0.8rem; -> 두 요소 간 간격 조정
  
<img width="179" alt="image" src="https://github.com/user-attachments/assets/52f98399-4573-432b-848c-0746a1e64bf7">
<img width="195" alt="image" src="https://github.com/user-attachments/assets/8172ba32-2809-4bc9-9db1-c3baaed4f89c">

2024-11-27 09:20 UTC, wonill commented on src/modals/RegisterAvatarModal/styles.ts
> +export const CustomActionButtonAfter = styled(BaseCustomActionButton)``
selectedAvatar를 BaseCustomActionButton의 prop으로 넣어서 조건에 따라 스타일을 다르게 주면 CustomActionButtonAfter 과 CustomActionButtonBefore를 만들지 않아도 되겠네요

2024-11-27 09:43 UTC, kimjuyoung99 commented on src/modals/RegisterAvatarModal/styles.ts
> +export const CustomActionButtonAfter = styled(BaseCustomActionButton)``
오 isSelected 값을 boolean 값으로 prop으로 보내주니까 간결해지네요~
리펙토링 했어요 감사합니다

2024-11-27 10:13 UTC, saseungmin approved these changes
고생하셨어요! 😊

2024-11-27 10:13 UTC, saseungmin commented on src/modals/RegisterAvatarModal/index.tsx
> +  const initialIndex = initialSelectedAvatar ? avatarImages.findIndex(avatar => avatar === initialSelectedAvatar) : null
`findIndex`인 경우 존재하지 않는 경우에 `-1`을 리턴하게 되어요!
그래서 `initialSelectedAvatar`는 있지만, `avatarImages`에 없는 경우에 -1이 반환하게 되는데, -1인 경우가 의도된게 아니라면, `undefined`를 반환하는 `find` 메서드를 사용하는게 적절해보이네요!

2024-11-27 10:13 UTC, saseungmin commented on src/modals/RegisterAvatarModal/index.tsx
> +  const [selectedAvatar, setSelectedAvatar] = useState<number | null>(initialIndex)
`initialIndex`인 경우에 렌더링과 상관없이 처음만 동작해야하는게 명확하다면, `useState`에서 lazy Initial로 처리해주는 방법도 있으니 고려해보세요! 지금 상황에서는 큰 비용은 안들어서 사실 큰차이는 없어요~ ㅎㅎ

```ts
const [selectedAvatar, setSelectedAvatar] = useState<number | null>(
  () => initialSelectedAvatar ? avatarImages.findIndex(avatar => avatar === initialSelectedAvatar) : null
)
```

https://www.pumpkiinbell.com/blog/react-hooks/useState/useState-lazy-initialization

2024-11-27 10:13 UTC, saseungmin commented on src/modals/RegisterAvatarModal/index.tsx
> +          <S.CharacterArea key={index} index={index} onClick={() => handleSelectAvatar(index)}>
index로 key를 관리하는 방식은 지양해야해요~
이유는 react에서 list를 렌더링할 때, rerender와 reconciliation와 연관이 있는데요~

기본적으로 react DOM 노드의 자식에서 재귀적으로 실행될 때 React는 두 자식 목록을 동시에 반복하고 차이가 있을 때마다 새로운 변형을 생성해요.

공식문서에 있는 내용을 가져와봤어요.

```jsx
<ul>
  <li>Duke</li>
  <li>Villanova</li>
</ul>

// Connecticut 아이템 추가
<ul>
  <li>Connecticut</li>
  <li>Duke</li>
  <li>Villanova</li>
</ul>
```

예를 들어, key가 없을 경우에 `Connecticut`의 item이 추가가 된 경우에 두개의 자식이 같음에도 불구하고, 모든 자식을 리랜더링하게 되어요. 그래서 react에서는 reconciliation 기반으로 비교 알고리즘이 동작하는데, 이때 리스트 사용 시에 key를 넣어야하는 휴리스틱 알고리즘으로 적용해야해요~

key는 언제나 불변해야한다는 조건이 있는데 index로 넣을때에는 값이 추가가될때 매번 불변하다는 보장이 없기 때문에, 불필요한 렌더링이 발생하는 것이에요~

이렇게 로컬 데이터라 id가 없는 경우에는 공식문서에서 제안하는 것처럼 [Crypto randomUUID](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID) 또는 [uuid](https://www.npmjs.com/package/uuid)와 같은 라이브러러리를 사용해서 넣어주면 좋아요!

```jsx
const avatarImages = Object.values(avatars).map((avatar, index) => ({ id: uuidv4(), image: avatar }))
```


https://react.dev/learn/rendering-lists#rendering-data-from-arrays

2024-11-27 10:13 UTC, saseungmin commented on src/pages/RegisterPage/Register/index.tsx
> +  const handleSelectAvatar = (avatarSrc: string): void => {
이미 타입추론이 되기 때문에 `void`로 return type 선언은 불필요해보여요~

2024-11-27 10:13 UTC, saseungmin commented on src/modals/RegisterAvatarModal/styles.ts
> +export const CustomActionButtonAfter = styled(BaseCustomActionButton)``
요거는 제가 전체적인 코드 맥락은 파악하지 않은점은 참고해주세요~

- 어떤 특정 도메인의 특정 조건에 따라서 prop로 넘겨주는 방식은 그 props를 위한 분기처리가 생길 수 있어, 나중에 거대한 레거시 컴포넌트가 될 수 있는 점 주의해주세요! 
- 공통적으로 사용하고 있는거라면 props도 공통으로 사용하는 props를 넘겨주고, 그 외의 경우에는 결합도를 올리는 방법보단, 합성하는 형태의 컴포넌트를 만드는게 좋습니다~
- 주영님께서 말씀주신 이름으로 인한 통일성을 주는거라면 빈 styled를 감싸는 방식은 좋은 방식이 아닌 것 같아보입니다~ 그냥 써도 괜찮을 것 같아요!

2024-11-27 19:30 UTC, wonill approved these changes, later dismissed

2024-11-28 01:03 UTC, kimjuyoung99 commented on src/modals/RegisterAvatarModal/styles.ts
> +export const CustomActionButtonAfter = styled(BaseCustomActionButton)``
구체적이고 친절한 피드리뷰 정말 감사드립니다!🥹 공부해서 적용해 보겠습니다~

2024-11-28 01:31 UTC, shlee9999 commented on src/modals/RegisterAvatarModal/index.tsx
> +  const [selectedAvatar, setSelectedAvatar] = useState<number | null>(initialIndex)
@saseungmin 주신 링크의 글 잘 읽어보았습니다. 
게으른 초기화가 useCallback과 비슷하게 동작한다고 생각했었는데
알아보니 게으른 초기화는 첫 렌더링 시에만 딱 한 번 실행하는 것이고
useCallback은 함수의 반환값을 메모이제이션을 하는 것일 뿐
함수의 실행 자체를 막지는 못해서 결국 리렌더링 시에도 계속 함수가 호출되는 것이라고 이해했습니다.
제가 이해한 게 맞나요?

2024-11-28 01:31 UTC, shlee9999 commented on src/modals/RegisterAvatarModal/index.tsx
> +      </S.HeaderArea>
코드 블록 안씌웠더니 코드가 아예 사라졌네요 수정했습니다!

2024-11-28 01:46 UTC, shlee9999 commented on src/modals/RegisterAvatarModal/index.tsx
> +          <S.CharacterArea key={index} index={index} onClick={() => handleSelectAvatar(index)}>
@saseungmin 제 개인적인 생각으로는 이 avatars처럼 절대 순서가 변경되거나 삭제되지 않을 컴포넌트에 대해서는 index를 키값으로 사용하더라도 괜찮다고 생각하는데, 어떻게 생각하시나요?

2024-11-28 01:57 UTC, saseungmin commented on src/modals/RegisterAvatarModal/index.tsx
> +  const [selectedAvatar, setSelectedAvatar] = useState<number | null>(initialIndex)
@shlee9999 

> 게으른 초기화가 useCallback과 비슷하게 동작한다고 생각했었는데
알아보니 게으른 초기화는 첫 렌더링 시에만 딱 한 번 실행하는 것이고

이거는 정확하게 이해하셨어요!

> useCallback은 함수의 반환값을 메모이제이션을 하는 것일 뿐
함수의 실행 자체를 막지는 못해서 결국 리렌더링 시에도 계속 함수가 호출되는 것이라고 이해했습니다.

이거는 잘못 이해하신 것 같아요~ 해당 내용이 블로그 글에 없는 내용인 것 같긴하네요~

useCallback은 함수 자체를 메모이제이션해요~ 즉, 의존성 배열이 변경되지 않는 한 동일한 함수 참조를 유지하죠!
리렌더링이 발생할 때, 
`useCallback`을 사용하지 않은 경우는 매 렌더링마다 새로운 함수가 생성되지만,
`useCallback`을 사용한 경우에는 의존성이 변경되지 않으면 이전에 생성된 동일한 함수를 재사용해요!

간단한 예시를 작성해봤는데, 

https://codesandbox.io/p/sandbox/practical-banzai-5kc9z4?workspaceId=ecff7117-dfec-4eb5-b8b0-f8a2bc9e98cc

콘솔을 켜보고, input에 값을 입력해보면 그 차이를 알 수 있어요~
`useCallback`은 단순히 반환값을 메모이제이션하는 것이 아니라, 함수 자체의 참조를 메모이제이션하여 불필요한 함수 재생성과 리렌더링을 최적화하는 hook이라고 생각해주시면 될 것 같아요~

2024-11-28 02:07 UTC, shlee9999 commented on src/modals/RegisterAvatarModal/index.tsx
> +  const [selectedAvatar, setSelectedAvatar] = useState<number | null>(initialIndex)
상세한 답변 감사합니다 😃 
제가 최적화 경험이 적어 혼선이 있었네요.
말씀하신 대로 useCallback은 함수 객체의 참조를 메모이제이션하는 것이고
함수의 반환값을 메모이제이션하는 건 useMemo였던 것 같습니다.
그렇다면 useCallback으로 메모이제이션 한 함수를 useState의 초깃값으로 사용하는 것과
게으른 초기화를 사용하는 것의 차이가 있을까요?
제가 생각하기엔 게으른 초기화는 단순히 첫 렌더링 시에만 해당 함수를 실행시키고 메모리는 사용하지 않는다고 생각되고
useCallback은 메모리를 더 잡아먹어 성능 상 게으른 초기화가 더 좋을 것 같습니다만, 제 생각이 맞을까요?

2024-11-28 02:42 UTC, shlee9999 approved these changes, later dismissed

2024-11-28 02:42 UTC, shlee9999 commented on src/pages/RegisterPage/Register/styles.ts
> +  font-weight: 700;
ActionButton prop으로 $fontWeight가 존재합니다

2024-11-28 10:56 UTC, saseungmin commented on src/modals/RegisterAvatarModal/index.tsx
> +  const [selectedAvatar, setSelectedAvatar] = useState<number | null>(initialIndex)
@shlee9999 

넵! 맛습니다~ ㅎㅎ
보통 `useCallback`을 사용해서 state의 lazy initialization를 같이 사용하지 않아요~
말씀주신대로 `useCallback`은 메모리에 저장을 해두기 때문에, 성능 최적화를 위한 정말 필요한 곳에서만 사용하는게 좋습니다!

`useCallback`과 `useMemo`는 언제 사용하는게 좋을까는 제가 정리해둔 글인데 한번 참고해주세요~

https://saseungmin.github.io/frontend-tech-interview/docs/react/when-to-useMemo-and-useCallback

2024-11-28 11:01 UTC, saseungmin commented on src/modals/RegisterAvatarModal/index.tsx
> +          <S.CharacterArea key={index} index={index} onClick={() => handleSelectAvatar(index)}>
@shlee9999 

저는 정적인 상태여도 index는 최대한 안사용하는 편입니다~ 그 정적인 상태의 데이터가 언제 변할지 모르는 것이고, [react 공식문서](https://react.dev/learn/rendering-lists#where-to-get-your-key)에서도 관련한 내용에 제안하는 것처럼 [Crypto randomUUID](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID) 또는 [uuid](https://www.npmjs.com/package/uuid)와 같은 라이브러러리를 사용하라고 했기 때문에 index는 언제든 사용하지 않는 편이에요~

eslint-react rule을 사용해보면 error로 나타나는것도 알 수 있어요~
https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md

2024-11-29 03:40 UTC, wonill approved these changes

2024-11-29 03:48 UTC, shlee9999 approved these changes

2024-11-29 03:48 UTC, merged